=== jiehang123/SrcBooksAndFrameworks/config-tools/autumn_xsd/autumn-components-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.jiehang.com/autumn/schema/components"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.jiehang.com/autumn/schema/components"
            elementFormDefault="qualified">
    <xsd:element name="components">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:choice minOccurs="0" maxOccurs="unbounded">
                    <xsd:element ref="component"/>
                </xsd:choice>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="component">
        <xsd:complexType>
            <xsd:attribute name="name" type="xsd:string"></xsd:attribute>
            <xsd:attribute name="class" type="xsd:string"></xsd:attribute>
            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                <xsd:element ref="property" />
            </xsd:choice>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="property">
        <xsd:complexType>
            <xsd:attribute name="name" type="xsd:string"></xsd:attribute>
        </xsd:complexType>
    </xsd:element>

</xsd:schema>

=== jiehang123/SrcBooksAndFrameworks/FrameworkForIoc/src/test/resources/autumnContext.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns="http://www.jiehang.com/autumn/schema/components"
            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="http://www.jiehang.com/autumn/schema/components
                http://www.jiehang.com/autumn/schema/components/autumn-components-1.0.xsd">

    <component name="simpleController" class="com.jiehang.autumn.bean.SimpleController">
        <property name="fundService">fundService</property>
    </component>

    <component name="fundService" class="com.jiehang.autumn.bean.FundServiceImpl">
        <property name="fundDao">fundDao</property>
    </component>

    <component name="fundDao" class="com.jiehang.autumn.bean.FundDaoImpl">
    </component>

    <component name="simpleProcessor" class="com.jiehang.autumn.bean.SimpleProcessor">
        <property name="guidService">guidService</property>
    </component>

    <component name="guidService" class="com.jiehang.autumn.bean.GuidServiceImpl">
        <property name="guidDao">guidDao</property>
        <property name="tradeDao">tradeDao</property>
    </component>

    <component name="guidDao" class="com.jiehang.autumn.bean.GuidDaoImpl">
    </component>

    <component name="tradeDao" class="com.jiehang.autumn.bean.TradeDaoImpl">
    </component>
</components>
